### ISSUE TITLE
Please explain what's wrong

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/HSHS-DOMXSS-Scanner#18]
Previously this read

> Everything is 100% except for one bonus and the overall score is 95%. Why?

The questions now merely are

1. What would be the proper text to display?
2. What do we need to do to achieve 100% for CSP? Isn't a sha256 hash safe enough?

![bildschirmfoto 2018-04-24 um 14 44 22](https://user-images.githubusercontent.com/725404/39187602-0a7e02fc-47ce-11e8-9052-67cd85a44868.png)

```JSON
{
  "name": "HEADER",
  "hasError": false,
  "errorMessage": null,
  "score": 95,
  "tests": [{
    "name": "CONTENT_SECURITY_POLICY",
    "hasError": false,
    "errorMessage": null,
    "score": 75,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "CSP_NO_UNSAFE_INCLUDED",
      "values": [{
        "HEADER": "\"default-src 'self'; script-src 'self' 'sha256-GDawD7jO073hEjCl6AdkNG1dWLYFcTlSuyzyFuGqZ0k=' https:\\\/\\\/webstats.eco.de; style-src 'self' https:\\\/\\\/fonts.googleapis.com; img-src 'self' https:\\\/\\\/siwecos.de https:\\\/\\\/webstats.eco.de data:; font-src 'self' https:\\\/\\\/fonts.gstatic.com;\""
      }]
    }]
  }, {
    "name": "CONTENT_TYPE",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "CT_META_TAG_SET_CORRECT",
      "values": {
        "META": "<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\" \/>"
      }
    }, {
      "placeholder": "CT_CORRECT",
      "values": {
        "HEADER": "text\/html; charset=UTF-8"
      }
    }]
  }, {
    "name": "PUBLIC_KEY_PINS",
    "hasError": true,
    "errorMessage": "HEADER_NOT_SET",
    "score": 0,
    "scoreType": "bonus",
    "testDetails": []
  }, {
    "name": "STRICT_TRANSPORT_SECURITY",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "HSTS_MORE_6",
      "values": []
    }, {
      "placeholder": "INCLUDE_SUBDOMAINS",
      "values": []
    }]
  }, {
    "name": "X_CONTENT_TYPE_OPTIONS",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "XCTO_CORRECT",
      "values": []
    }]
  }, {
    "name": "X_FRAME_OPTIONS",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "XFO_CORRECT",
      "values": []
    }]
  }, {
    "name": "X_XSS_PROTECTION",
    "hasError": false,
    "errorMessage": null,
    "score": 100,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "XXSS_CORRECT",
      "values": []
    }, {
      "placeholder": "XXSS_BLOCK",
      "values": []
    }]
  }]
}
```

**Comment by Skeeve** [comment]
Correction. @ic0ns noticed: CSP is at 75%, not at 100.

So the overall score is clear. Just the message is misleading :(

```
Der Header ist korrekt gesetzt und enthält keine `unsafe-`-Direktiven.
```

So what's wrong here? How could we fix it.

Please note: There is no other way (we found) to make the "script-src" work. It's inline script in an svg which is required to not make the "SIWECOS-Seal" overly complicated. Having a script hash seems reasonably safe to me.

**Comment by Lednerb** [comment]
The problem is not about the `script-src` directive.

It's caused by the `default-src` definition.
At the moment you get the following rating:

https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/master/app/Ratings/CSPRating.php#L37-L44

Only if you set `default-src: none` and also do not include `unsafe-*` definitions 
you can get the score of 100.
Using a hash is fine and does not affect the rating.

-------------------------------------

Maybe there is a better way of validating a secure CSP but for this implementation there was the following idea:


**In general:**
`default-src: none` should be used to avoid XSS-Attacks via other (not defined) directives.

**Case 1:** If there's a `default-src: self` and no `script-src`.
An attacker can run code that was inserted via XSS or an unfiltered input, a malicious `script`-tag can run without an error.

**Case 2:** There is a `default-src: none` but also `script-src: self`;
The same code as in Case 1 would work but the admin that set the CSP should know about the options `self` give.

The idea is that in Case 2 the CSP-admin is aware of the potential risks, so the rating would be a score of 100, otherwise 75.

**Case 3:** There is a `default-src: none` and the `script-src:` always with a hash.
The attacker from Case 1 and Case 2 is not successful because he cannot insert the correct hash into the header. 
The site is secure and so the rating is 100.

**Comment by Skeeve** [comment]
So what should be the proper text for "CSP_NO_UNSAFE_INCLUDED"?

Please note: The text displayed is ONLY based on the placeholder (possibly merging in values) and NEVER based on the score. But looking at your code it seems "CSP_NO_UNSAFE_INCLUDED" is always coming with score 75, right?

**Comment by Skeeve** [comment]
Additional questions besides
1. What is the proper text to display
are
2. What's the problem with the combination `default-src 'self'` and `script-src 'self' 'sha156-…'`
3. I think there is an issue with your tests for default-src:

```JSON
{
    "name": "CONTENT_SECURITY_POLICY",
    "hasError": false,
    "errorMessage": null,
    "score": 75,
    "scoreType": "warning",
    "testDetails": [{
      "placeholder": "CSP_NO_UNSAFE_INCLUDED",
      "values": [{
        "HEADER": "\"default-src  'none'; script-src 'self' 'sha256-GDawD7jO073hEjCl6AdkNG1dWLYFcTlSuyzyFuGqZ0k=' https:\\\/\\\/webstats.eco.de; style-src 'self' https:\\\/\\\/fonts.googleapis.com; img-src 'self' https:\\\/\\\/siwecos.de https:\\\/\\\/webstats.eco.de data:; font-src 'self' https:\\\/\\\/fonts.gstatic.com;\""
      }]
    }]
  }
```

**Comment by Lednerb** [comment]
`CSP_NO_UNSAFE_INCLUDED` is always scored with 75 points.
The score 100 gets the placeholder `CSP_CORRECT`.

https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/master/app/Ratings/CSPRating.php#L40-L43

-------------------------

Text to display:
`CSP_CORRECT` - Die CSP ist korrekt eingestellt.
`CSP_NO_UNSAFE_INCLUDED` - Die CSP enthält keine `unsafe-` Direktiven, ist möglicherweise jedoch nicht sicher eingestellt.

------------------------

> What's the problem with the combination `default-src 'self'` and `script-src 'self' 'sha156-…'`
There's no problem with it. It's just not implemented as a testcase at the moment.
We should open a feature request issue to implement this case and rate it with a score of 100.

-----------------------

> I think there is an issue with your tests for default-src:

Seems that the error is caused by the additional whitespace between `default-src` and `'none'` because there's no regex search but a static for `default-src 'none'` here:

https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/master/app/Ratings/CSPRating.php#L41

**Comment by Skeeve** [comment]
> Seems that the error is caused by the additional whitespace between default-src and 'none' because there's no regex search but a static for default-src 'none' here:

I know. ;) Will you fix it?

**Comment by Lednerb** [comment]
Done by #20, please check.
